[package]
name = "framework_toolbox"
version = "0.7.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
dirs = "5.0.1"
iced = { version = "0.12.1", features = ["tokio"] }
serde = { version = "1.0.197", features = ["derive"] }
strum = "0.26.2"

