[package]
name = "framework_toolbox"
version = "0.1.0"
edition = "2021"

default-run = "fwtb"

[[bin]]
name = "fwtb"
path = "src/main.rs"

[[bin]]
name = "fwtbd"
path = "src/bin/daemon.rs"

[dependencies]
anyhow = "1.0.66"
iced = { git = "https://github.com/iced-rs/iced", rev = "77c8380", features = ["tokio"] }
os_pipe = "1.1.1"
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
