[package]
name = "framework_toolbox"
version = "0.1.0"
edition = "2021"

default-run = "framework_toolbox"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", rev = "77c8380", features = ["tokio"] }
os_pipe = "1.1.1"
serde = { version = "1.0.145", features = ["derive"] }
toml = "0.5.9"
